'use client';

import React, { useState } from 'react';
import { 
  Feature, 
  ScreenItem, 
  JourneyNodeData, 
  JourneyEdgeData, 
  KnowledgeItem, 
  QACheckpoint, 
  QAObservation, 
  AIQuestion 
} from '@/lib/types';
import { 
  Download, 
  FileText, 
  FileSpreadsheet, 
  Check, 
  Copy, 
  Share2, 
  Sparkles,
  Layers,
  Printer
} from 'lucide-react';
import jsPDF from 'jspdf';
import Papa from 'papaparse';

interface ExportStudioProps {
  feature: Feature;
  screens: ScreenItem[];
  nodes: JourneyNodeData[];
  edges: JourneyEdgeData[];
  knowledge: KnowledgeItem[];
  checkpoints: QACheckpoint[];
  observations: QAObservation[];
  questions: AIQuestion[];
}

export function ExportStudio({
  feature,
  screens,
  nodes,
  edges,
  knowledge,
  checkpoints,
  observations,
  questions
}: ExportStudioProps) {
  const [copied, setCopied] = useState(false);

  // Generate Master Markdown Document
  const generateMarkdown = () => {
    return `# Feature Intelligence Specification: ${feature.name}
**Application**: ${feature.name} | **Platform**: ${feature.platform} | **Version**: v${feature.version}
**Date Generated**: ${new Date().toLocaleDateString()} | **QA Governance Engine**: AetherQA

---

## 1. Executive Summary & Purpose
- **Description**: ${feature.description}
- **Primary Purpose**: ${feature.purpose}
- **Starting Point**: \`${feature.entry_point}\`
- **Expected Outcome**: \`${feature.expected_outcome}\`

## 2. Target User Types & Privileges
${feature.user_types.map(u => `- **${u}**: Standard role privileges verified for this journey.`).join('\n')}

## 3. Screen Sequence & Empirical Evidence (${screens.length} Screens)
${screens.map(s => `### Screen #${s.screen_number}: ${s.name}
- **State**: \`${s.state}\`
- **User Action**: ${s.user_action || 'N/A'}
- **System Response**: ${s.expected_behavior || 'N/A'}
- **Observed Elements**: ${(s.ai_analysis?.elements || []).map(e => e.label).join(', ') || 'N/A'}
- **Image Reference**: ${s.image_url}
`).join('\n')}

## 4. Visual User Journey Transitions (DAG Structure)
${edges.map(e => `- \`${e.source_node_id}\` ──[ **${e.action}** / *${e.system_response}* ]──> \`${e.target_node_id}\` (${e.edge_type})`).join('\n')}

## 5. 7 Core Knowledge Pillars
${knowledge.map(k => `### [${k.category}] ${k.title}
- **Confidence**: \`${k.confidence}\` | **Source**: ${k.source} | **Status**: ${k.verification_status}
- **Specification**: ${k.content}
- **Notes**: ${k.notes || '—'}
`).join('\n')}

## 6. QA Verification Checkpoints Matrix (${checkpoints.length} Tests)
| Category | Checkpoint Title | Test Procedure | Expected Result | Priority | Status |
| :--- | :--- | :--- | :--- | :--- | :--- |
${checkpoints.map(c => `| ${c.category} | ${c.title} | ${c.test_steps.replace(/\n/g, ' ')} | ${c.expected_result} | ${c.priority} | ${c.status} |`).join('\n')}

## 7. Flagged Defect Observations & UX Issues (${observations.length})
${observations.map(o => `- **[${o.type} - ${o.priority}] ${o.title}**: ${o.description} (Severity: ${o.severity}, Status: ${o.status})`).join('\n')}

## 8. Clarified Unknowns & AI Questions (${questions.length})
${questions.map(q => `- **Q**: ${q.question}\n  - **Resolution**: ${q.answer || 'Pending confirmation'} (\`${q.status}\`)`).join('\n')}

---
*Generated by AetherQA Clinical Operating System.*
`;
  };

  const handleDownloadMarkdown = () => {
    const md = generateMarkdown();
    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `${feature.name.replace(/\s+/g, '_')}_Feature_Package.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(generateMarkdown());
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleExportPDF = () => {
    const doc = new jsPDF();
    
    // Clinical header
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.text(`Feature QA Package: ${feature.name}`, 14, 20);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.text(`Application: ${feature.name} (${feature.platform}) | Version: ${feature.version}`, 14, 28);
    doc.text(`Generated: ${new Date().toLocaleDateString()} | AetherQA Clinical Operating System`, 14, 34);

    doc.setDrawColor(220, 221, 214);
    doc.line(14, 38, 196, 38);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text('1. Overview & Purpose', 14, 46);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.text(`Description: ${feature.description}`, 14, 54, { maxWidth: 180 });
    doc.text(`Starting Point: ${feature.entry_point}`, 14, 66);
    doc.text(`Expected Outcome: ${feature.expected_outcome}`, 14, 72);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text(`2. Screens Sequenced (${screens.length})`, 14, 84);

    let y = 92;
    screens.slice(0, 5).forEach((s) => {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.text(`Screen #${s.screen_number}: ${s.name} [${s.state}]`, 14, y);
      doc.setFont('helvetica', 'normal');
      doc.text(`Action: ${s.user_action || 'N/A'} -> Response: ${s.expected_behavior || 'N/A'}`, 14, y + 5);
      y += 12;
    });

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text(`3. Core Knowledge Items (${knowledge.length})`, 14, y + 4);
    y += 12;

    knowledge.slice(0, 6).forEach((k) => {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.text(`[${k.category}] ${k.title} (${k.confidence})`, 14, y);
      doc.setFont('helvetica', 'normal');
      doc.text(`${k.content.substring(0, 95)}...`, 14, y + 5);
      y += 12;
    });

    doc.save(`${feature.name.replace(/\s+/g, '_')}_QA_Package.pdf`);
  };

  const handleExportCSV = () => {
    const csvData = checkpoints.map(cp => ({
      Category: cp.category,
      Title: cp.title,
      Steps: cp.test_steps.replace(/\n/g, ' | '),
      ExpectedResult: cp.expected_result,
      Priority: cp.priority,
      Status: cp.status
    }));

    const csv = Papa.unparse(csvData);
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `${feature.name.replace(/\s+/g, '_')}_Checkpoints.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="flex-1 flex flex-col h-full overflow-hidden p-4 sm:p-6 space-y-6">
      
      {/* Top Banner */}
      <div className="bg-clinical-white p-4 rounded-2xl border border-clinical-border shadow-subtle flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <span className="w-2.5 h-2.5 rounded-full bg-neon animate-pulse" />
          <div>
            <h3 className="text-xs font-bold text-dark-chassis tracking-tight">
              MASTER EXPORT & HANDOFF STUDIO
            </h3>
            <p className="text-[11px] text-txt-secondary">
              Generate enterprise-grade QA artifacts for developers, business analysts, and compliance audits.
            </p>
          </div>
        </div>

        <button
          onClick={handleCopyMarkdown}
          className="px-4 py-1.5 rounded-pill bg-clinical-warm hover:bg-clinical-border text-dark-chassis text-xs font-bold border border-clinical-border flex items-center gap-1.5 transition"
        >
          {copied ? <Check className="w-3.5 h-3.5 text-status-positive" /> : <Copy className="w-3.5 h-3.5" />}
          {copied ? 'Copied to Clipboard!' : 'Copy Complete Markdown'}
        </button>
      </div>

      {/* Export Options Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        
        {/* Master Package PDF */}
        <div className="bg-clinical-white rounded-2xl border border-clinical-border p-5 shadow-card flex flex-col justify-between space-y-4">
          <div className="space-y-2">
            <div className="w-10 h-10 rounded-full bg-dark-chassis text-neon flex items-center justify-center">
              <Printer className="w-5 h-5" />
            </div>
            <h4 className="text-sm font-bold text-dark-chassis">Executive QA Package (PDF)</h4>
            <p className="text-xs text-txt-secondary leading-relaxed">
              Clinical summary document including feature scope, screen flows, business rules, and test sign-offs.
            </p>
          </div>
          <button
            onClick={handleExportPDF}
            className="w-full py-2 rounded-pill bg-dark-chassis text-white text-xs font-semibold hover:bg-dark-secondary flex items-center justify-center gap-2 transition"
          >
            <Download className="w-3.5 h-3.5" />
            Download PDF Report
          </button>
        </div>

        {/* Markdown Spec */}
        <div className="bg-clinical-white rounded-2xl border border-clinical-border p-5 shadow-card flex flex-col justify-between space-y-4">
          <div className="space-y-2">
            <div className="w-10 h-10 rounded-full bg-neon/30 text-dark-chassis flex items-center justify-center">
              <FileText className="w-5 h-5" />
            </div>
            <h4 className="text-sm font-bold text-dark-chassis">Living Markdown Specification</h4>
            <p className="text-xs text-txt-secondary leading-relaxed">
              Complete GitHub-flavored markdown with all 15 sections formatted with tables and evidence links.
            </p>
          </div>
          <button
            onClick={handleDownloadMarkdown}
            className="w-full py-2 rounded-pill bg-neon text-dark-chassis text-xs font-bold hover:bg-neon-bright flex items-center justify-center gap-2 transition shadow-sm"
          >
            <Download className="w-3.5 h-3.5" />
            Download Markdown (.md)
          </button>
        </div>

        {/* QA Checkpoints Spreadsheet */}
        <div className="bg-clinical-white rounded-2xl border border-clinical-border p-5 shadow-card flex flex-col justify-between space-y-4">
          <div className="space-y-2">
            <div className="w-10 h-10 rounded-full bg-status-positive/20 text-status-positive flex items-center justify-center">
              <FileSpreadsheet className="w-5 h-5" />
            </div>
            <h4 className="text-sm font-bold text-dark-chassis">TestRail / Jira QA Matrix (CSV)</h4>
            <p className="text-xs text-txt-secondary leading-relaxed">
              Formatted test cases ready for bulk import into TestRail, Jira Xray, or Zephyr.
            </p>
          </div>
          <button
            onClick={handleExportCSV}
            className="w-full py-2 rounded-pill bg-clinical-warm text-dark-chassis border border-clinical-border text-xs font-semibold hover:bg-clinical-surface flex items-center justify-center gap-2 transition"
          >
            <Download className="w-3.5 h-3.5" />
            Download CSV Matrix
          </button>
        </div>

      </div>

      {/* Package Live Preview */}
      <div className="flex-1 bg-clinical-white rounded-2xl border border-clinical-border p-4 shadow-card overflow-hidden flex flex-col">
        <div className="flex items-center justify-between border-b border-clinical-border pb-2 mb-2 text-xs">
          <span className="font-bold text-dark-chassis">LIVE ARTIFACT PREVIEW</span>
          <span className="text-txt-muted font-mono">{screens.length} screens • {knowledge.length} items • {checkpoints.length} tests</span>
        </div>
        <pre className="flex-1 overflow-auto text-[11px] font-mono p-3 bg-clinical-warm rounded-xl text-txt-primary leading-relaxed select-all">
          {generateMarkdown()}
        </pre>
      </div>

    </div>
  );
}
